const serverProtocol = `https`
// const serverAddress = `server-telefon.duckdns.org/` //localhost
const subDomain = `server-telefon`
const domain = `duckdns`
const topDomain = `org`
// const serverPort = `4200`
const serverEntry = `api`
// export const baseUrl = `${serverProtocol}://${serverAddress}:${serverPort}/${serverEntry}`;
export const localUrl = `${serverProtocol}://${subDomain}.${domain}.${topDomain}/${serverEntry}`
export const baseUrl = `http://localhost:4200/api`//`${serverProtocol}://${subDomain}.${domain}.${topDomain}/${serverEntry}`
export const socketEndpoint = `http://localhost:4200` 
export const socketLocal = `https://server-telefon.duckdns.org`